#!/bin/bash
# test the 20_dt_probe driver
source ../common
DRV=dt_probe
DTB=testoverlay.dtbo

make || die "make failed"
echo
sudo rmmod ${DRV} 2>/dev/null || true
sudo dmesg -C
sudo insmod ${DRV}.ko || die "failed to insmod"

# trigger it
sudo dtoverlay ${DTB}

runcmd "sudo dmesg"
